export const GET_USER = 'GET_USER'
export const GET_TOKEN = 'GET_TOKEN'
export const GET_USER_TRACKLIST = 'GET_USER_TRACKLIST'
export const PLAY_TRACK = 'PLAY_TRACK'
export const RESUME_TRACK = 'RESUME_TRACK'
export const PAUSE_TRACK = 'PAUSE_TRACK'
export const ERROR = 'ERROR'
