export const GET_TRACKLIST = 'GET_TRACKLIST'
export const SET_TRACK = 'SET_TRACK'
export const PLAY_TRACK = 'PLAY_TRACK'
export const RESUME_TRACK = 'RESUME_TRACK'
export const PAUSE_TRACK = 'PAUSE_TRACK'
export const NEXT_TRACK = 'NEXT_TRACK'
export const PREVIOUS_TRACK = 'PREVIOUS_TRACK'
export const ERROR = 'ERROR'
